server:
  port: 8081
spring:
  profiles:
    #运行的环境
    active: prod
  application:
    name: hmdp
  datasource:
    url: jdbc:mysql://${chat.mysql.ip}:${chat.mysql.port}/${chat.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${chat.mysql.username}
    password: ${chat.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # Redis服务器地址
    host: ${chat.redis.host}
    # Redis服务器端口号
    port: ${chat.redis.port}
    # 设置密码
    password: ${chat.redis.password}
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug